import React, { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css?v=portfolio-comments-13';
import './typography.css';


const Island = lazy(() => import('./Island.jsx'));


const projectCategories = ['All projects', 'Web development', 'Mobile', 'AI / ML', 'Data', 'UI/UX', 'Vibe Coding'];
const projects = [
  { title:'Loop', category:'Web development', image:'project-loop-trimmed.png', description:'A community-driven web app for NYC residents to report incidents, share updates, post events, and chat in real time. Built with a team of four.', tags:['Community','Real-time','Team project'], stack:['React','Vite','Google Maps API','Node.js','Express.js','MongoDB','Socket.io'], live:'https://capstonefall2025-frontend.onrender.com/', github:'https://github.com/CSCI-40500-Fall-2025/project-project-9' },
  { title:'Lifted', category:'Mobile', categories:['Mobile','AI / ML','Data'], image:'project-lifted.png', description:'A mental wellness mobile app created with a team of four. Includes AI therapist conversations, daily emotion check-ins, mood tracking, and an interactive Book of Answers.', tags:['Wellness','AI','Team project'], stack:['React Native','Expo','Express.js','PostgreSQL','OpenAI API'], github:'https://github.com/CSCI-40500-Fall-2025/project-project-9' },
  { title:'SerendiQuest', category:'AI / ML', categories:['AI / ML','Web development'], image:'project-serendiqust-trimmed.png', description:'An AI-powered, location-based adventure web app that creates personalized prompts to help people explore their surroundings in unexpected ways.', tags:['Generative AI','Web app'], stack:['React','Google Maps API','Node.js','Express.js','MongoDB','Gemini API'], live:'https://serendiquest.onrender.com/', github:'https://github.com/ReinaC26/csci-39548-project' },
  { title:'ZipNote', category:'Web development', categories:['Web development'], image:'project-zipnote.jpg', description:'A colorful, interactive web application for capturing thoughts and ideas instantly.', tags:['Productivity','Web app'], stack:['React','Vite','Node.js','Express.js','MongoDB'], live:'https://personal-note-app-six-three.vercel.app/', github:'https://github.com/ReinaC26/Personal-Note-App' },
  { title:'VisualDive', category:'Mobile', image:'project-visualdive.jpg', description:'An iOS app designed for those who need to quickly discover, organize, and compare inspirational visual content for their social media posts, presentations, and creative personal projects.', tags:['iOS app','Visual discovery'], stack:['Swift'], github:'https://github.com/ReinaC26/VisualDive' },
  { title:'Between the Bites', category:'Web development', categories:['Web development'], image:'project-between-bites.jpg', description:'A website concept for a fictional brunch restaurant, designed to bring its menu and personality to life.', tags:['Brand concept','Web app'], stack:['React','Node.js','Express.js','MongoDB'], live:'https://between-the-bites.onrender.com/', github:'https://github.com/ReinaC26/Restaurant-Website-React', githubAlt:'https://github.com/ReinaC26/Restaurant-Website' },
  { title:'Food Fresh', category:'Web development', categories:['Web development'], image:'project-food-fresh-new.jpg', description:'A pantry tracker that helps people organize and manage ingredients, so everyday essentials are easier to keep on hand.', tags:['Utility','Web app'], stack:['Next.js','React','Material UI','Firebase'], live:'https://pantry-tracker-app-gold.vercel.app/', github:'https://github.com/ReinaC26/Pantry-Tracker' },
  { title:'Cat Post', category:'UI/UX', image:'project-cat-post.jpg', description:'Cat Post connects people through e-postcards, giving them a place to share ideas, moments from daily life, and more.', tags:['e-postcard','Social connection','Figma'], stack:['Figma'], live:'https://www.figma.com/design/jDSRE7lvumsE1PIV0TfXRp/Hackathon-Project?node-id=246-400&p=f&t=q1fdd6zOebvxQ1TF-0' },
];
const experiences = [
  { date:'JUN — AUG 2026', place:'INFORMATION TECHNOLOGY INTERN', title:'Information Technology Intern', org:'American Civil Liberties Union', details:[
    'Built a Power BI dashboard combining Zendesk, Asana, and network data. Modeled 13K+ tickets and 100+ IT tasks across 21 groups and 101 organizations to surface workload trends and improvement opportunities.',
    'Mapped three onboarding workflows for national, affiliate, and intern roles; identified access, permission, and process gaps with partner teams to support standardization.',
    'Helped migrate 250+ NY and DC Cisco desk phones to Teams Calling. Contributed to the rollout and phone configuration, wrote a user guide, and held office hours to resolve post-migration issues.'
  ] },
  { date:'MAR — MAY 2026', place:'MENTORSHIP PROGRAM', title:'Software Engineering Program Participant', org:'Code2Career (Basta × Google)', description:'Selected as 1 of 250 students from 1,500 applicants for a 10-week mentorship with a Google Software Engineer, focused on improving data structures and algorithms through complex code challenges and technical interviews.' },
  { date:'JUL — SEP 2024', place:'FELLOWSHIP', title:'Software Engineering Fellow', org:'Headstarter AI', description:'Built and deployed AI projects over five weeks using React, Next.js, Firebase, Clerk, Stripe, OpenAI, and Vercel.' },
  { date:'FEB — MAY 2024', place:'ONLINE CLASS', title:'Web Development', org:'CodePath', description:'Built a Resource Finder for people new to America and practiced responsive page structure, HTML, CSS, JavaScript, and flexbox layouts.' },
  { date:'FEB 2024', place:'HACKATHON', title:'HackCUNY 2024', org:'CUNY', description:'Joined an in-person hackathon selected from 300 signups. Designed an NYC community app in Figma to help people pause, connect, and share e-postcards.' },
  { date:'JAN 2024', place:'TECHNOLOGY INTERN', title:'Technology Intern', org:'Morgan Stanley', details:[
    'Researched the technical context and collaborated with engineering teams to assist with infrastructure architecture planning and solution design for Terraform Cloud for Business.',
    'Created and codified 3 architecture choices into a series of diagrams, evaluated the pros and cons of each option, and provided a recommendation that was ultimately adopted by the team to guide future design.'
  ] },
  { date:'SEP 2022 — JAN 2024', place:'CAMPUS LEADERSHIP', title:'Event Planning Committee Lead', org:'Chinese Student and Scholar Association at Hunter', description:'Planned and executed 10+ campus events of varying scale, running post-event assessments to refine future programming. Grew social media following to 1,000+ across platforms.' },
  { date:'SEP 2023', place:'JOB SIMULATION', title:'Software Engineering Job Simulation', org:'New York Jobs CEO Council · Forage', description:'Debugged a critical billing issue and added an invoice note feature.' },
  { date:'NOV 2022', place:'1ST PLACE · 10+ PARTICIPATING TEAMS', title:'Girls Who Code × Hunter WiCS Hackathon', org:'Hunter College', description:'Led a team of four to build a website addressing gender equity in tech and won 1st place among 10+ teams.' },
];
const skillGroups = [
  {category:'UI/UX',items:['Figma','Wireframing','Prototyping']},
  {category:'Programming Languages',items:['Python','C++','JavaScript','SQL','HTML','CSS','Swift']},
  {category:'Frontend Dev',items:['React','Next.js']},
  {category:'Backend Dev',items:['Node.js','Express.js']},
  {category:'Data',items:['Power BI','MongoDB','Neo4j','MySQL','PostgreSQL','Firebase']},
  {category:'AI',items:['LLM APIs · OpenAI, Gemini, Claude']},
  {category:'Tools',items:['Git/GitHub','Codex','Claude Code','Microsoft 365']},
];
const interests = [
  {title:'Photography',description:'Capturing moments and telling visual stories through the lens',photos:[{image:'photography/photo-01.jpg',alt:'People resting beneath a tree beside the water'},{image:'photography/photo-02.jpg',alt:'Origami birds displayed in a sunlit window'},{image:'photography/photo-03.jpg',alt:'Brooklyn Bridge and Manhattan skyline at dusk'},{image:'photography/photo-04.jpg',alt:'Fireworks over a fairytale castle at night'},{image:'photography/photo-05.jpg',alt:'Sunlight on a stone wall and quiet street'},{image:'photography/photo-06.jpg',alt:'Rainbow appearing over a tree-lined neighborhood'}]},
  {title:'Design',description:'Creation guided by my aesthetic perspective',photos:[{image:'design-visualdive.png',alt:'VisualDive mobile app design flow'},{image:'design-floating-island.png',alt:'Floating island portfolio scene'},{image:'design-zipnote.png',alt:'ZipNote interface wireframe'}]},
  {title:'More',description:'More photos of my life',photos:[{image:'more/gym-treadmill.jpg',alt:'Treadmill console at the gym'},{image:'more/mario-kart.jpg',alt:'Mario Kart race results on a screen'},{image:'more/sunlit-cat.jpg',alt:'Cat resting on a sunlit ledge'},{image:'more/ceramic-painting.jpg',alt:'Paintbrushes and ceramic pieces at an art studio'},{image:'more/dinner-table.jpg',alt:'Dinner dishes shared around a restaurant table'},{image:'more/picnic-meal.jpg',alt:'Picnic meal spread on a checkered blanket'}]},
];
const landmarks = [
  { id:'projects', title:'Projects', note:'Ideas made real', icon:'star' },
  { id:'experience', title:'Experience', note:"Where I've grown", icon:'tree' },
  { id:'skills', title:'Skills', note:'Tools I work with', icon:'house' },
  { id:'contact', title:'Contact', note:"Let's say hello", icon:'bridge' },
];
function Mark({ name, size=20 }) {
  const common={width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.65,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true};
  const shapes={star:<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>,tree:<><path d="m12 3 7 8h-4l4 5h-5v5h-4v-5H5l4-5H5l7-8Z"/><path d="M12 21v-5"/></>,house:<><path d="m3 11 9-7 9 7"/><path d="M5.5 10v10h13V10M10 20v-6h4v6"/></>,bridge:<><path d="M3 18h18M5 18V9m14 9V9M5 10c4-5 10-5 14 0M8 12v6m4-7v7m4-7v7"/><path d="M2 21h20"/></>,arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,compass:<><circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2.25 4.75L8.5 15.5l2.25-4.75L15.5 8.5Z"/></>};
  return <svg {...common}>{shapes[name]||shapes.compass}</svg>;
}
function FilterBar({label,categories,selected,onSelect}){return <div className="filter-bar" role="group" aria-label={label}>{categories.map(c=><button className={`filter-button${selected===c?' is-selected':''}`} type="button" key={c} aria-pressed={selected===c} onClick={()=>onSelect(c)}>{c}</button>)}</div>}
function Header(){return <header className="topbar"><a className="brand" href="#home" aria-label="Reina Chen, home"><span className="brand-mark">S</span><span className="brand-copy">REINA CHEN<small>MY ISLAND OF IDEAS</small></span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a></nav><a className="header-contact" href="#contact">Let's connect <Mark name="arrow" size={14}/></a></header>}
function Hero({showScene}){return <section className="hero" id="home" aria-labelledby="hero-title"><div className="intro"><h1 id="hero-title">Welcome to<br/><em>Reina's Island.</em></h1><p className="intro-location"><span className="location-line"/> A PORTFOLIO BY REINA CHEN</p><p className="lede">Hello! I'm ShiJie (Reina) Chen, a designer and developer. I create at the intersection of design and technology.</p><a className="path-link" href="#about">A little about me <Mark name="arrow" size={17}/></a><p className="drag-hint"><span className="hint-dot"/> Drag to turn <span aria-hidden="true">·</span> Scroll to explore</p></div><div className="island-wrap"><div className="island-art" aria-label="Interactive floating storybook island. Drag to rotate and use the wheel or pinch to zoom.">{showScene?<Suspense fallback={<div className="scene-loading" role="status"><span className="loading-orbit"/><span>Bringing the island into view…</span></div>}><Island/></Suspense>:<div className="scene-loading" role="status"><span className="loading-orbit"/><span>Bringing the island into view…</span></div>}</div>{landmarks.map(x=><a className={`scene-label label-${x.id}`} href={`#${x.id}`} key={x.id}><span className="label-icon"><img src={`/icons/sections/${x.icon}.png`} alt="" width="26" height="26"/></span><span className="label-copy"><strong>{x.title}</strong><small>{x.note}</small></span></a>)}</div></section>}
function LandmarkRail(){return <nav className="landmark-rail" aria-label="Island landmarks"><span className="rail-label">THE ISLAND PATH</span>{landmarks.map((x,i)=><a href={`#${x.id}`} key={x.id}><span className="rail-node"><Mark name={x.icon} size={15}/></span><span>{x.title}</span>{i<landmarks.length-1&&<span className="rail-rule"/>}</a>)}</nav>}
function InterestCard({item}){const galleryRef=useRef(null),[position,setPosition]=useState({left:0,max:0});const updatePosition=()=>{const gallery=galleryRef.current;if(gallery)setPosition({left:gallery.scrollLeft,max:gallery.scrollWidth-gallery.clientWidth})};useEffect(()=>{const gallery=galleryRef.current;if(!gallery)return;const observer=new ResizeObserver(updatePosition);observer.observe(gallery);gallery.addEventListener('scroll',updatePosition,{passive:true});gallery.querySelectorAll('img').forEach(img=>img.addEventListener('load',updatePosition));updatePosition();return()=>{observer.disconnect();gallery.removeEventListener('scroll',updatePosition);gallery.querySelectorAll('img').forEach(img=>img.removeEventListener('load',updatePosition))}},[]);const move=direction=>{const gallery=galleryRef.current;if(!gallery)return;const step=gallery.clientWidth;gallery.scrollBy({left:direction*step,behavior:'smooth'});setPosition({left:gallery.scrollLeft,max:gallery.scrollWidth-gallery.clientWidth})};return <article className="interest-card" aria-label={item.title}><div className="interest-gallery" ref={galleryRef} role="region" aria-label={`${item.title} photos`} tabIndex="0">{item.photos.map(photo=><img key={photo.image} src={`/images/portfolio/${photo.image}`} alt={photo.alt} loading="lazy"/>)}</div><div className="interest-copy"><strong>{item.title}</strong><span>{item.description}</span></div><button className="interest-scroll-control interest-scroll-previous" type="button" aria-label={`Previous ${item.title} photo`} disabled={position.left<=1} onClick={()=>move(-1)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg></button><button className="interest-scroll-control interest-scroll-next" type="button" aria-label={`Next ${item.title} photo`} disabled={position.left>=position.max-1} onClick={()=>move(1)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></button></article>}
function About(){return <section className="about-section section-frame" id="about" aria-labelledby="about-title"><div className="about-copy"><span className="section-index">ABOUT ME</span><h2 id="about-title">Get to know me</h2><p>I love and enjoy photography, design, and solving puzzle games.</p></div><figure className="about-portrait"><img src="/images/portfolio/reina-portrait.jpg" alt="ShiJie (Reina) Chen"/><figcaption>SHIJIE (REINA) CHEN<span>DESIGNER &amp; DEVELOPER</span></figcaption></figure><div className="interest-strip" aria-label="Reina's interests">{interests.map(item=><InterestCard item={item} key={item.title}/>)}</div></section>}
function Experience(){return <section className="experience-section section-frame" id="experience" aria-labelledby="experience-title"><div className="section-heading"><div><span className="experience-heading-leaf" aria-hidden="true"><img src="/images/portfolio/experience-leaf.png" alt=""/></span><span className="section-index">EXPERIENCE</span><h2 id="experience-title">Growth <em>path</em></h2></div></div><ol className="timeline" aria-label="Experience timeline">{experiences.map((x,i)=><li className={`timeline-empty timeline-item timeline-item--${i%2?'right':'left'}`} key={`${x.org}-${x.title}`}><span className="timeline-node"><span>{String(i+1).padStart(2,'0')}</span></span><article className="timeline-entry"><span className="timeline-date">{x.date} · {x.place}</span><h3>{x.title}</h3><strong className="timeline-org">{x.org}</strong><ul className="timeline-bullets">{(x.details||[x.description]).map((detail,j)=><li key={j}>{detail}</li>)}</ul></article></li>)}</ol><a className="quiet-link resume-link" href="https://drive.google.com/drive/u/0/folders/1T5TTUJ5zttIno0MZ_UxLig6kBhPmMO6B" target="_blank" rel="noreferrer">View Resume <Mark name="arrow" size={21}/></a></section>}
function Projects({selected,setSelected}){const shown=selected==='All projects'?projects:projects.filter(x=>(x.categories||[x.category]).includes(selected));return <section className="projects-section section-frame" id="projects" aria-labelledby="projects-title"><div className="section-heading"><div><h2 id="projects-title">When <em>My Ideas</em> Come to Life</h2><span className="section-index">PROJECTS</span></div><p>Select a category from the filter to explore</p></div><FilterBar label="Filter projects by category" categories={projectCategories} selected={selected} onSelect={setSelected}/><div className="project-grid">{shown.map(x=><article className="project-entry" key={x.title}><a className={`project-image${x.title==='Cat Post'?' project-image-cat-post':''}${x.title==='VisualDive'?' project-image-visualdive':''}`} href={x.live||x.github||'#projects'} target={x.live||x.github?'_blank':undefined} rel="noreferrer"><img loading="lazy" src={`/images/portfolio/${x.image}`} alt={`${x.title} project preview`}/></a><div className="project-meta"><span>{x.category}</span><span>{x.tags.join(' · ')}</span></div><h3>{x.title}</h3><p>{x.description}</p><div className="project-stack" aria-label={`${x.title} technology stack`}><span className="project-stack-label">Built with</span><ul>{x.stack.map(technology=><li key={technology}>{technology}</li>)}</ul></div><div className="project-links">{x.live&&<a href={x.live} target="_blank" rel="noreferrer">Visit project <Mark name="arrow" size={13}/></a>}{x.github&&<a href={x.github} target="_blank" rel="noreferrer">{x.githubAlt?"Source code (React)":"Source code"} <Mark name="arrow" size={13}/></a>}{x.githubAlt&&<a href={x.githubAlt} target="_blank" rel="noreferrer">Source code (HTML/CSS/JavaScript) <Mark name="arrow" size={13}/></a>}</div></article>)}</div>{shown.length===0&&<div className="collection-empty" role="status"><div><h3>Vibe Coding</h3><p>No projects in this category yet.</p></div></div>}</section>}
function Skills(){return <section className="skills-section section-frame" id="skills" aria-labelledby="skills-title"><div className="section-heading"><div><span className="section-index">SKILLS</span><h2 id="skills-title">Technology &amp; <em>craft stack</em></h2></div></div><div className="skill-groups">{skillGroups.map(group=><article className="skill-group" key={group.category}><h3>{group.category}</h3><ul>{group.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></section>}
function Contact(){const sendMessage=event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=encodeURIComponent(`Portfolio message from ${data.get('name')}`);const body=encodeURIComponent(`From: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`);window.location.href=`mailto:chensj0314@gmail.com?subject=${subject}&body=${body}`};return <section className="contact-section section-frame" id="contact" aria-labelledby="contact-title"><div className="contact-visual" aria-hidden="true"><img src="/images/portfolio/contact-bridge.jpg" alt="" loading="lazy"/></div><div className="contact-copy"><span className="section-index">CONTACT</span><h2 id="contact-title">Let's create<br/><em>something meaningful</em></h2><p>Have a role, idea, or question? Let's Chat!</p><div className="contact-links"><a href="mailto:chensj0314@gmail.com">Email</a><a href="https://www.linkedin.com/in/shijie-reina-chen/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/ReinaC26" target="_blank" rel="noreferrer">GitHub</a></div></div><form className="contact-form" onSubmit={sendMessage}><h3>Send a note</h3><div className="contact-fields"><label>Name<input name="name" autoComplete="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label></div><label>Message<textarea name="message" required rows="4" placeholder="What would you like to talk about?"/></label><button type="submit">Let's Chat <Mark name="arrow" size={17}/></button></form></section>}
function App(){const [showScene,setShowScene]=useState(false),[selectedProject,setSelectedProject]=useState(projectCategories[0]);useEffect(()=>{const id=window.setTimeout(()=>setShowScene(true),120);return()=>window.clearTimeout(id)},[]);return <><a className="skip-link" href="#main-content">Skip to content</a><Header/><div className="sky-shell"><main id="main-content"><Hero showScene={showScene}/><div className="about-divider" aria-hidden="true"/><About/><Experience/><Projects selected={selectedProject} setSelected={setSelectedProject}/><Skills/><Contact/></main><footer><span>© 2026 REINA CHEN</span></footer></div></>}
createRoot(document.getElementById('root')).render(<App/>);

